#!/bin/bash
export ROOT_DIR=$(pwd)

export TCL_VERSION=8.6.13
export TK_VERSION=8.6.13
export QT_VERSION=5.14.2
export HDF5_VERSION=1.12.2
export TINYXML2_VERSION=6.2.0
export PYTHON_VERSION=3.9.10
export PYTHON_MAJOR_VERSION=3
export PYTHON_MINOR_VERSION=9
export FREETYPE_VERSION=2.6.3
export SWIG_VERSION=3.0.12
export MMG_VERSION=5.3.9
export GDCM_VERSION=2.6.3
export OPENCASCADE_VERSION=7.6.0
export PIP_VERSION=0.0.0
export NUMPY_VERSION=1.14.3
export ML_VERSION=1.0.0
export VTK_VERSION=9.2.6
export ITK_VERSION=5.2.1
export MITK_VERSION=2022.10

# set library location environment variables

CUR_DIR=$(pwd)

# set directories
export SRC_DIR=$CUR_DIR'/src'
export INSTALL_DIR=$CUR_DIR'/install'
export PATCH_DIR=$CUR_DIR'/patches'

# TCL

TCL_MAJOR_VERSION=${TCL_VERSION%.*}
export TCL_LIB_NAME=libtcl$TCL_MAJOR_VERSION.so
export TCL_EXE_NAME=tclsh$TCL_MAJOR_VERSION
export TCL_INSTALL_DIR=$INSTALL_DIR/tcl-$TCL_VERSION

# TK

TK_MAJOR_VERSION=${TK_VERSION%.*}
export TK_LIB_NAME=libtk$TK_MAJOR_VERSION.so
export TK_EXE_NAME=wish$TK_MAJOR_VERSION
export TK_INSTALL_DIR=$INSTALL_DIR/tk-$TK_VERSION

# Qt

export QT_INSTALL_DIR=$INSTALL_DIR/qt-$QT_VERSION
export QT_INSTALL_DIR_CMAKE=$QT_INSTALL_DIR/lib/cmake/Qt5/

# HDF5

export HDF5_INSTALL_DIR=$INSTALL_DIR/hdf5-$HDF5_VERSION
export HDF5_CMAKE_DIR=$HDF5_INSTALL_DIR/cmake

# Tinyxml2

export TINYXML2_INSTALL_DIR=$INSTALL_DIR/tinyxml2-$TINYXML2_VERSION
export TINYXML2_INSTALL_DIR_CMAKE=$TINYXML2_INSTALL_DIR/lib/cmake/tinyxml2/

# Python
export PYTHON_EXECUTABLE=bin/python3
export PYTHON_INCLUDE_DIR=include/python3.9
export PYTHON_LIBRARY=lib/libpython3.9.so
export PYTHON_INSTALL_DIR=$INSTALL_DIR/python-$PYTHON_VERSION
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PYTHON_INSTALL_DIR/lib

# Freetype 

export FREETYPE_INSTALL_DIR=$INSTALL_DIR/freetype-$FREETYPE_VERSION
export FREETYPE_LIBRARY=libfreetype.so.$FREETYPE_VERSION

# Swig

export SWIG_INSTALL_DIR=$INSTALL_DIR/swig-$SWIG_VERSION
export SWIG_EXECUTABLE=$SWIG_INSTALL_DIR/bin/swig

# Mmg

export MMG_INSTALL_DIR=$INSTALL_DIR/mmg-$MMG_VERSION

# Gdcm

GDCM_MAJOR_VERSION=${GDCM_VERSION%.*}
export GDCM_INSTALL_DIR=$INSTALL_DIR/gdcm-$GDCM_VERSION
export GDCM_INCLUDE_DIR=$GDCM_INSTALL_DIR/include/gdcm-$GDCM_MAJOR_VERSION
export GDCM_CMAKE_DIR=$GDCM_INSTALL_DIR/lib/gdcm-$GDCM_MAJOR_VERSION

# VTK

VTK_MAJOR_VERSION=${VTK_VERSION%.*}
export VTK_INSTALL_DIR=$INSTALL_DIR/vtk-$VTK_VERSION
export VTK_CMAKE_DIR=$VTK_INSTALL_DIR/lib/cmake/vtk-$VTK_MAJOR_VERSION

# ITK 

ITK_MAJOR_VERSION=${ITK_VERSION%.*}
export ITK_INSTALL_DIR=$INSTALL_DIR/itk-$ITK_VERSION
export ITK_INSTALL_DIR_CMAKE=$ITK_INSTALL_DIR/lib/cmake/ITK-$ITK_MAJOR_VERSION

# Opencascade

export OPENCASCADE_INSTALL_DIR=$INSTALL_DIR/opencascade-$OPENCASCADE_VERSION

# Mitk

export MITK_INSTALL_DIR=$INSTALL_DIR/mitk-$MITK_VERSION










