# This is a basic workflow that is manually triggered

name: Build SimVascular Externals - Linux

# Controls when the action will run.
on:
  # Workflow runs when manually triggered using the UI or API.
  workflow_dispatch:
        
  # This is to schedule run every Monday at 5:30 UTC
  schedule:
    # Runs every monday at 5:30 UTC
    - cron: '30 5 * * 1'
    
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-mitk-ubuntu-20:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract dependencies
        shell: bash
        run: |
          mkdir -p install
          cd install
          wget http://simvascular.stanford.edu/downloads/public/simvascular/externals/2022.10/linux/ubuntu/20.04/gnu/7.5/x64/release/2022.10.13/ubuntu.20.04.gnu.7.5.x64.release.2022.10.13.mitk.2022.10.tar.gz_old.tar.gz
          tar -xvf ubuntu.20.04.gnu.7.5.x64.release.2022.10.13.mitk.2022.10.tar.gz_old.tar.gz

      - name: Install MITK
        shell: bash
        run: |
          mkdir -p src
          source env_variables.sh
          source scripts/post-install-mitk.sh
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: MITK Install
          path: install/mitk.tar
          if-no-files-found: error

  
        
    

    
