# This is a basic workflow that is manually triggered

name: Build SimVascular Externals - Mac

# Controls when the action will run.
on:
  # Workflow runs when manually triggered using the UI or API.
  workflow_dispatch:
        
  # This is to schedule run every Monday at 5:30 UTC
  schedule:
    # Runs every monday at 5:30 UTC
    - cron: '30 5 * * 1'
    
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-libraries-macos-11:
    runs-on: macos-11
    steps:
    # Checkout the repository first
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build libraries for MacOS
      shell: bash
      run: |
        bash build_all.sh
        tar -cf SVExternals-MacOS-11.tar install
        tar -cf BuildOutput-MacOS-11.tar output
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: SVExternals MacOS 11
        path: SVExternals-MacOS-11.tar
        if-no-files-found: error

    - name: Upload output artifact
      uses: actions/upload-artifact@v3
      with:
        name: Output MacOS 11
        path: BuildOutput-MacOS-11.tar
        if-no-files-found: error

  build-libraries-macos-12:
    runs-on: macos-12
    steps:
    # Checkout the repository first
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build libraries for MacOS
      shell: bash
      run: |
        bash build_all.sh
        tar -cf SVExternals-MacOS-12.tar install
        tar -cf BuildOutput-MacOS-12.tar output
        
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: SVExternals MacOS 12
        path: SVExternals-MacOS-12.tar
        if-no-files-found: error

    - name: Upload output artifact
      uses: actions/upload-artifact@v3
      with:
        name: Output MacOS 12
        path: BuildOutput-MacOS-12.tar
        if-no-files-found: error
        
    
